### PR TITLE
Add a more production-esque docker-compose setup

### PR DESCRIPTION
**Pull request by MasterOdin**
Sets up the docker-compose to be more production ready. The MySQL details are now set through a `.env` file (as well as duplicated in the `.db_config.php` file). Adds a `docker-compose.override.yml` file that gets merged into the `docker-compose.yml` file unless you use the explicit `-f` flag (which is suggested for production).

Updates composer and bower to install for production when run within the container.

### CODE REVIEW

**Comment by ddbruce** [comment]
This is going to be run on a server running Docker and Traefik; therefore, there is already a `docker-compose.yml` file on the server. Will I be able to easily add this repo as a new service in that file with something like
```
services:
    [...]
    rpia-website:
        build: https://github.com/rpiambulance/website.git
        container_name: rpia-website
[...]
```
?

I know you have that `override` file, but I'm not sure how that works in the context of an existing Docker Compose config file. Also, you have a Docker Compose file in this repo, so I don't know how that interacts.


Thanks!

**Comment by MasterOdin** [comment]
The only thing then that affects that is the changes to the Dockerfile and the rest can be ignored.

**Comment by ddbruce** [comment]
@MasterOdin the change from `master` to `dev` (above) won't push to the live site, correct?

**Comment by MasterOdin** [comment]
No, Travis only runs deploy on pushes to master:
https://github.com/rpiambulance/website/blob/8a32bdb5c20f6b174a87db81d5fcd85f8d00d353/.travis.yml#L15-L18

**Pull request merged**
