### PR TITLE
Fix #44 - Edit Member Behavior

### LINKED ISSUE #44: Edit Member doesn't work consistently
If you were to edit a member and make them a driver lets say, to take that away you have to check, uncheck, check, uncheck. One simple uncheck doesn't seem to work and allows the user to keep their position. This has caused confusion with many people using this feature.

### PR DESCRIPTION
**Pull request by alexmattoni**
Fixes #44. Angular docs [say](https://docs.angularjs.org/api/ng/directive/ngChecked) use of "ng-model" and "ng-checked" together can create the unexpected behavior. Changed to use "ng-true-value" and "ng-false-value" to properly sync the checkboxes.

### CODE REVIEW

**Review by ddbruce — COMMENTED** [review]
Is there a reason the 1s and 0s are all contained within double _and_ single quotes? Why `"'1'"` and not `"1"`?

**Comment by alexmattoni** [comment]
> Is there a reason the 1s and 0s are all contained within double _and_ single quotes? Why `"'1'"` and not `"1"`?

The additional single quotes quotes define them as strings, it doesn't compare properly otherwise.

This also supersedes the `value='1'` field so I just got rid of those.

**Comment by ddbruce** [comment]
For future reference, the behavior mentioned [above](https://github.com/rpiambulance/website/pull/156#issuecomment-1544330372) is because `EditMemberCtrl.js` at line 257:

https://github.com/rpiambulance/website/blob/3379de9e0a08b3fa8cc9f585eeff6f271be3338f/js/controllers/EditMemberCtrl.js#L257-L263

compares to a string.

**Review by ddbruce — APPROVED** [review]

**Comment by tceluzza** [comment]
These changes were approved, are we good to merge?

**Comment by ddbruce** [comment]
Unless we wanted to not compare to a string as mentioned above

**Comment by tceluzza** [comment]
> For future reference, the behavior mentioned [above](https://github.com/rpiambulance/website/pull/156#issuecomment-1544330372) is because `EditMemberCtrl.js` at line 257:
> 
> https://github.com/rpiambulance/website/blob/3379de9e0a08b3fa8cc9f585eeff6f271be3338f/js/controllers/EditMemberCtrl.js#L257-L263
> 
> compares to a string.

I'm not sure this is the right explanation. That section is for the officer/coordinator position dropdown, not the crew positions/trainings completed - the checkboxes that we've had issues with (there ARE some issues with the officer/coordinator dropdown, which is why I figure `NoNe1` exists at all, but that's not what's fixed here.

If you remove the extra quotes, it works correctly in that it sets the values in the backend but it doesn't _show_ correctly on the edit member page. I think this is because of member_table.php`'s use of json_encode when retrieving the member's info. It converts the ints in the database to strings. One way around this, as used for the yes/no questions (admin, active, revoked) is to post-process/parse them into ints:

https://github.com/rpiambulance/website/blob/ca5322c2ccd9def29fdb9473dcbb7ab36686312d/js/controllers/EditMemberCtrl.js#L171-L173

**Comment by ddbruce** [comment]
Good enough for me. I don't even remember writing my "for future reference" comment above, so I can't currently speak to its accuracy.

**Pull request merged**
