### PR TITLE
Adds a navbar for the scheduling coordinator.

### LINKED ISSUE #35: Scheduling Coordinator does not have a navigation dropdown
Currently scheduling coordinator has to memorize the hyperlinks needed to modify the schedule and edit the default schedule. These options are prevalent under the admin navigation bar menu and therefore should exist under a specific navigation menu for them.

### PR DESCRIPTION
**Pull request by lramos15**
This adds a navigation bar item for the scheduling coordinator. It seems to work pretty well, however it seems like the navbar gets stuck when the user logs out. I think it's because the logout process isn't completing correctly and is a side effect of the issue I have open that clicking home logs the user out. This fixes #35

### CODE REVIEW

**Comment by lramos15** [comment]
Before nav bar items could be only listed as admin only and shows up for only admins. This allows nav bar items to be listed as scheduling only as well and only show for scheduling coordinator.

**Comment by ddbruce** [comment]
I understand the logic behind what you're trying to do, but I can't wrap my head around `(!n.adminOnly && !isAdmin) || (!n.schedulingOnly && !isScheduling)`. Why does this work? I might not understand what the vars are, I guess.

**Comment by lramos15** [comment]
I believe it can also be written as `(!n.adminOnly || isAdmin) || (!n.schedulingOnly || isScheduling)` which might make it easier to wrap the brain around.

**Comment by lramos15** [comment]
@ddbruce  you were correct the if statement logic was incorrect and is now much more.... logical.

**Pull request merged**
