### PR TITLE
Grievance Report Page

### LINKED ISSUE #173: Provide an option to file a grievance on the website
Provide a web form so members can file a grievance report directly from the website. We could complete this with an embeded google form or a custom web form.

### PR DESCRIPTION
**Pull request by alexmattoni**
Adds a page for an embedded GC report form. Blurb provided and approved by GC. Resolves #173.

Placed under 'Tools' dropdown (due to it being a fillable form, like the fuel log or stocking pages, as well as overcrowding of the 'Resources' dropdown). It's center jutisifed like the stocking page.

Screenshot 2024-03-12 at 10 00 00 AM

### CODE REVIEW

**Comment by ddbruce** [comment]
Does the GC work on int**er**agency issues or just int**ra**agency issues?

**Comment by alexmattoni** [comment]
proof read what they sent and updated

**Comment by alexmattoni** [comment]
Also added officers & 5939 updates.

**Comment by ddbruce** [comment]
Lgtm though untested because I'm on my phone

**Review by ddbruce — APPROVED** [review]

**Pull request merged**
